/**
 * ERD-Pipeline Step 2: schema-model.json → Mermaid-Diagramme + draw.io + HTML-Viewer
 *
 * Liest die Transfer-Datei aus Step 1 und erzeugt in spec/erd/generated/:
 *   - big-picture.mmd            alle Tabellen, nur Kanten (Übersicht)
 *   - erd.drawio                 draw.io: alle Tabellen nach Kategorie gefärbt
 *   - categories/<key>.mmd       eine Mermaid-Datei je Kategorie
 *   - categories/<key>.drawio    eine draw.io-Datei je Kategorie
 *   - entities/<name>.mmd       eine Mermaid-Datei je Tabelle (alle Felder)
 *   - entities/<name>.drawio     eine draw.io-Datei je Tabelle (Felder + Nachbarn)
 *   - erd.html                  statischer Viewer, Diagramm-Quellen INLINED —
 *                                funktioniert auch via file:// ohne Server
 *
 * Hand-editiert bleibt nur spec/erd/schema.sql. Regenerieren: pnpm erd:build
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { renderMarkdown } from "./markdown-to-html";
import type { SchemaModel, Table } from "./parse-schema";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const MODEL_PATH = join(REPO_ROOT, "spec", "erd", "generated", "schema-model.json");
const OUT_DIR = join(REPO_ROOT, "spec", "erd", "generated");

// Optional: Markdown-Tab im Viewer. Fehlt die Datei, bleibt der Tab leer.
const NICHT_CRUD_SOURCE_DIR = "spec/erd";
const NICHT_CRUD_SOURCE_FILE = "nicht-crud-katalog.md";
const VIEWER_OUTPUT_DIR = "spec/erd/generated";

const model: SchemaModel = JSON.parse(readFileSync(MODEL_PATH, "utf-8"));

// Business-Beschreibung je Tabelle — Zweck im Fachmodell, nicht technisch.
// Wird in Entity-Liste, Kategorie-Karten und der Detail-Ansicht gezeigt.
// Die technischen desc-Werte aus schema.sql bleiben unverändert dort stehen.
const businessDescriptions: Record<string, string> = {};
const businessDescriptionsShort: Record<string, string> = {};
const tablesByName = new Map(model.tables.map((t) => [t.name, t]));
const categoryColorByKey = new Map(model.categories.map((c) => [c.key, c.color]));

const FALLBACK_CATEGORY_COLOR = "#64748b";

function categoryColor(category: string): string {
  return categoryColorByKey.get(category) ?? FALLBACK_CATEGORY_COLOR;
}

/** CSS aus dem Schema-Modell — Variablen für :root, Klassen als eigene Regeln. */
function categoryCssVars(): string {
  return model.categories
    .map((category) => {
      const safe = category.key.replace(/[^a-zA-Z0-9_-]/g, "-");
      return `    --cat-${safe}: ${category.color};`;
    })
    .join("\n");
}

function categoryCssClasses(): string {
  return model.categories
    .map((category) => {
      const safe = category.key.replace(/[^a-zA-Z0-9_-]/g, "-");
      return `  .cat-${safe} { color: var(--cat-${safe}); }`;
    })
    .join("\n");
}

// ---------------------------------------------------------------------------
// Mermaid-Quellen
// ---------------------------------------------------------------------------

function mermaidHeader(title: string): string {
  return [
    `%% ${title}`,
    "%% Generated by spark/scripts/erd/generate-diagrams.ts — do not edit by hand.",
    "%% Source: spec/erd/schema.sql (single source of truth)",
    "erDiagram",
  ].join("\n");
}

function nodeLabel(table: Table): string {
  const label = `${table.label} · ${table.columns.length} fields`.replace(/"/g, "'");
  return `${table.name}["${label}"]`;
}

// Audit-Kanten (created_by/updated_by/… → user) sind auf ~27 der 59 Kanten
// reine Buchhaltung. Sie alle in `user` münden zu lassen, macht jedes
// Übersichts-Diagramm unlesbar — sie gehören nur ins Entity-Detail.
const AUDIT_FK_COLUMNS = new Set([
  "created_by",
  "updated_by",
  "granted_by",
  "revoked_by",
  "changed_by",
  "actor_id",
]);

function isAuditEdge(edge: { fromColumn: string }): boolean {
  return AUDIT_FK_COLUMNS.has(edge.fromColumn);
}

// Mermaid erDiagram liest `A ||--o{ B` als "ein A, viele B". Eine FK-Spalte
// opportunity.owner_id → user.id bedeutet aber: viele Opportunities zeigen auf
// EINEN User — die Kante muss vom Parent zur Child-Tabelle laufen, also
// user ||--o{ opportunity. Die Diagramm-Kanten laufen deshalb entgegen der
// FK-Richtung: fromTable = referenzierte Tabelle, toTable = FK-Halter.
// Logische Referenzen (04 §5, 06 §6 — bewusst kein FK) laufen als `..` statt
// `--`: die offizielle erDiagram-Syntax fuer nicht-identifizierende
// Beziehungen, gerendert als gestrichelte Linie.
function diagramEdge(fromTable: string, toTable: string, label: string, dashed = false): string {
  const line = dashed ? ".." : "--";
  return `  ${fromTable} ||${line}o{ ${toTable} : "${label}"`;
}

function bigPictureMmd(): string {
  const lines = [mermaidHeader("Big Picture — all tables, business FK edges")];
  lines.push("  direction LR");
  for (const table of model.tables) {
    lines.push(`  ${nodeLabel(table)}`);
  }
  for (const edge of model.edges) {
    if (isAuditEdge(edge)) continue;
    lines.push(diagramEdge(edge.toTable, edge.fromTable, edge.fromColumn, edge.kind === "logical"));
  }
  return `${lines.join("\n")}\n`;
}

function categoryMmd(catKey: string): string {
  const category = model.categories.find((c) => c.key === catKey);
  if (!category) return "";
  const members = new Set(category.tables);
  const lines = [mermaidHeader(`Category: ${category.label} (${category.tables.length} tables)`)];
  lines.push("  direction LR");
  for (const tableName of category.tables) {
    const table = tablesByName.get(tableName);
    if (table) lines.push(`  ${nodeLabel(table)}`);
  }
  // erDiagram erlaubt keine %%-Kommentare am Zeilenende — Cross-Category
  // wird im Kanten-Label markiert.
  for (const edge of model.edges) {
    const fromInside = members.has(edge.fromTable);
    const toInside = members.has(edge.toTable);
    if (!fromInside && !toInside) continue;
    if (isAuditEdge(edge)) continue;
    const label = fromInside && toInside ? edge.fromColumn : `${edge.fromColumn} (cross)`;
    lines.push(diagramEdge(edge.toTable, edge.fromTable, label, edge.kind === "logical"));
  }
  return `${lines.join("\n")}\n`;
}

function entityMmd(name: string): string {
  const table = tablesByName.get(name);
  if (!table) return "";
  const label = table.label.replace(/"/g, "'");
  const lines = [mermaidHeader(`Entity: ${table.name} (${table.label})`)];
  lines.push(`  ${table.name}["${label}"] {`);
  for (const column of table.columns) {
    // Mermaid erDiagram-Attributtypen dürfen nur Wortzeichen enthalten —
    // Klammern und Klartext-Suffixe wie "(18)" brechen den Parser.
    const type = column.sqlType
      .toUpperCase()
      .replace(/[^A-Z0-9_]/g, "_")
      .replace(/_+/g, "_");
    const pk = column.isPrimaryKey ? " PK" : "";
    const fk = column.references ? " FK" : "";
    lines.push(`    ${type} ${column.name}${pk}${fk}`);
  }
  lines.push("  }");
  // Nachbar-Kanten: alles was auf diese Tabelle zeigt oder von ihr ausgeht.
  // Hier inklusive Audit-Kanten (im Entity-Detail ist jede Kante relevant).
  // Nicht deklarierte Gegenstellen rendert Mermaid automatisch als leere Box.
  for (const edge of model.edges) {
    if (edge.fromTable === table.name || edge.toTable === table.name) {
      lines.push(
        diagramEdge(edge.toTable, edge.fromTable, edge.fromColumn, edge.kind === "logical"),
      );
    }
  }
  return `${lines.join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// draw.io-XML
// ---------------------------------------------------------------------------

function xmlEscape(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function drawioWrap(diagramName: string, nodesXml: string, edgesXml: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<mxfile host="app.diagrams.net" modified="${new Date().toISOString()}" agent="erd-pipeline" version="24.0.0">
  <diagram id="${diagramName}" name="${diagramName}">
    <mxGraphModel dx="1400" dy="900" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="1600" pageHeight="1200" math="0" shadow="0">
      <root>
        <mxCell id="0"/>
        <mxCell id="1" parent="0"/>
${nodesXml}
${edgesXml}
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>
`;
}

function mxCellNode(
  id: string,
  htmlLabel: string,
  x: number,
  y: number,
  width: number,
  height: number,
  fill: string,
  fontColor: string,
  dashed = false,
): string {
  const style = `rounded=1;whiteSpace=wrap;html=1;fillColor=${fill};fontColor=${fontColor};${
    dashed ? "dashed=1;" : ""
  }strokeColor=${dashed ? "#94a3b8" : "none"}`;
  return `        <mxCell id="${id}" value="${xmlEscape(htmlLabel)}" style="${style}" vertex="1" parent="1">
          <mxGeometry x="${x}" y="${y}" width="${width}" height="${height}" as="geometry"/>
        </mxCell>`;
}

interface EdgeGeom {
  /** Zusätzliche Wegpunkte (mxPoint) — umleiten um störende Boxen. */
  points?: { x: number; y: number }[];
  /** Extra-Stil-Segmente (Anker, Versatz, Marker). */
  extraStyle?: string;
}

function mxCellEdge(
  id: string,
  source: string,
  target: string,
  label: string,
  geom: EdgeGeom = {},
  dashed = false,
): string {
  // Wegpunkte gehören bei Kanten mit source/target in ein Array as="points" —
  // mxPoint as="sourcePoint" wird nur bei freischwebenden Kanten gelesen.
  const pointsXml = geom.points
    ? `
          <Array as="points">${geom.points.map((p) => `<mxPoint x="${p.x}" y="${p.y}"/>`).join("")}</Array>`
    : "";
  // Logische Referenzen (04 §5, 06 §6 — bewusst kein FK) gestrichelt + grau,
  // damit sie sich von echten FK-Kanten unterscheiden.
  const style = `edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;fontSize=10;labelBackgroundColor=#ffffff;${
    dashed ? "dashed=1;strokeColor=#94a3b8;" : ""
  }${geom.extraStyle ? `${geom.extraStyle};` : ""}`;
  return `        <mxCell id="${id}" value="${xmlEscape(label)}" style="${style}" edge="1" parent="1" source="${source}" target="${target}">
          <mxGeometry relative="1" as="geometry">${pointsXml}
          </mxGeometry>
        </mxCell>`;
}

/** snake_case-FK-Spalten als lesbares Kanten-Label: owner_id → owner. */
function humanizeFkLabel(col: string): string {
  return col.replace(/_id$/, "").replace(/_/g, " ");
}

function compactLabel(table: Table): string {
  return `<b>${table.name}</b><br>${table.label} · ${table.columns.length} fields`;
}

function bigPictureDrawio(): string {
  const nodes: string[] = [];
  const edges: string[] = [];
  const idOf = new Map<string, string>();
  model.tables.forEach((table, i) => {
    idOf.set(table.name, `n${i}`);
  });

  const NODE_W = 220;
  const NODE_H = 70;
  const ROW_H = 110;
  const COL_W = 260;

  // Positionen vorab berechnen — die Kanten-Logik braucht Quelle/Ziel-Koordinaten.
  const pos = new Map<string, { x: number; y: number; catIdx: number; row: number }>();
  const rowsPerCategory = new Map<string, number>();
  model.tables.forEach((table) => {
    const rows = rowsPerCategory.get(table.category) ?? 0;
    rowsPerCategory.set(table.category, rows + 1);
  });
  // Bug 7: Spalten vertikal zentrieren, damit kurze Kategorien nicht oben kleben
  const maxRows = Math.max(...rowsPerCategory.values());
  const rowCounters = new Map<string, number>();
  model.tables.forEach((table, i) => {
    const catIdx = model.categories.findIndex((c) => c.key === table.category);
    const row = rowCounters.get(table.category) ?? 0;
    rowCounters.set(table.category, row + 1);
    const rows = rowsPerCategory.get(table.category) ?? 1;
    const centerOffset = ((maxRows - rows) / 2) * ROW_H;
    const x = catIdx * COL_W + 40;
    const y = row * ROW_H + 60 + centerOffset;
    pos.set(table.name, { x, y, catIdx, row });
    nodes.push(
      mxCellNode(
        idOf.get(table.name) ?? `n${i}`,
        compactLabel(table),
        x,
        y,
        NODE_W,
        NODE_H,
        categoryColor(table.category),
        "#ffffff",
      ),
    );
  });

  // Nur Business-Kanten (siehe isAuditEdge), in Parent→Child-Richtung
  // konsistent zur Mermaid-Ansicht.
  const businessEdges = model.edges.filter((e) => !isAuditEdge(e));

  // Bug 2: Parallele Kanten (gleiches source->target) fächern — jede bekommt
  // einen anderen exitY/entryY-Anker, gleichmäßig über die Box-Höhe verteilt.
  const parallelGroups = new Map<string, number>();
  for (const e of businessEdges) {
    const key = `${e.toTable}->${e.fromTable}`;
    parallelGroups.set(key, (parallelGroups.get(key) ?? 0) + 1);
  }
  const seenInGroup = new Map<string, number>();

  let edgeIndex = 0;
  for (const edge of businessEdges) {
    const sourceId = idOf.get(edge.toTable) ?? "";
    const targetId = idOf.get(edge.fromTable) ?? "";
    const key = `${edge.toTable}->${edge.fromTable}`;
    const groupSize = parallelGroups.get(key) ?? 1;
    const groupIdx = seenInGroup.get(key) ?? 0;
    seenInGroup.set(key, groupIdx + 1);
    const t = groupSize > 1 ? 0.2 + groupIdx * (0.6 / (groupSize - 1)) : -1;

    let extraStyle = "";
    const geom: EdgeGeom = {};

    if (edge.toTable === edge.fromTable) {
      // Bug 3: Selbstreferenz — Anker auf verschiedenen Seiten + Wegpunkt außen
      const p = pos.get(edge.toTable);
      extraStyle = "exitX=1;exitY=0.25;exitDx=0;exitDy=0;entryX=1;entryY=0.75;entryDx=0;entryDy=0";
      if (p) geom.points = [{ x: p.x + NODE_W + 40, y: p.y + 25 }];
    } else {
      const sp = pos.get(edge.toTable);
      const tp = pos.get(edge.fromTable);
      if (sp && tp && sp.catIdx === tp.catIdx && Math.abs(sp.row - tp.row) > 1) {
        // Bug 1: Same-Column-Multi-Hop — Linie durch die Spalte würde fremde
        // Boxen kreuzen; durch die linke Gutter-Zone außen herumführen.
        const gutterX = sp.x - 30;
        geom.points = [
          { x: gutterX, y: sp.y + 35 },
          { x: gutterX, y: tp.y + 35 },
        ];
      }
      if (t >= 0) {
        extraStyle = `exitY=${t.toFixed(2)};entryY=${t.toFixed(2)};exitDx=0;exitDy=0;entryDx=0;entryDy=0`;
      }
    }

    // Bug 5: Kardinalitätsmarker — genau ein Parent, null-oder-mehrere Children
    extraStyle = extraStyle
      ? `${extraStyle};startArrow=ERone;startFill=0;endArrow=ERmany;endFill=0`
      : "startArrow=ERone;startFill=0;endArrow=ERmany;endFill=0";

    edges.push(
      mxCellEdge(
        `e${edgeIndex}`,
        sourceId,
        targetId,
        humanizeFkLabel(edge.fromColumn),
        {
          ...geom,
          extraStyle,
        },
        edge.kind === "logical",
      ),
    );
    edgeIndex += 1;
  }
  return drawioWrap("erd-big-picture", nodes.join("\n"), edges.join("\n"));
}

function categoryDrawio(catKey: string): string {
  const category = model.categories.find((c) => c.key === catKey);
  if (!category) return "";
  const members = new Set(category.tables);
  const included = new Map<string, Table>();
  for (const tableName of category.tables) {
    const table = tablesByName.get(tableName);
    if (table) included.set(tableName, table);
  }
  // Cross-Category-Nachbarn als graue Knoten mit aufnehmen
  for (const edge of model.edges) {
    if (isAuditEdge(edge)) continue;
    const fromInside = members.has(edge.fromTable);
    const toInside = members.has(edge.toTable);
    if (fromInside && toInside) continue;
    if (!fromInside && !toInside) continue;
    for (const tableName of [edge.fromTable, edge.toTable]) {
      if (!members.has(tableName) && !included.has(tableName)) {
        const table = tablesByName.get(tableName);
        if (table) included.set(tableName, table);
      }
    }
  }

  const nodes: string[] = [];
  const edges: string[] = [];
  const idOf = new Map<string, string>();
  // Mitglieder zuerst (gefärbt), dann Nachbarn (grau, gestrichelt)
  const ordered = [...category.tables, ...[...included.keys()].filter((t) => !members.has(t))];
  ordered.forEach((tableName, i) => {
    const table = included.get(tableName);
    if (!table) return;
    idOf.set(tableName, `n${i}`);
    const isMember = members.has(tableName);
    const col = i % 3;
    const row = Math.floor(i / 3);
    nodes.push(
      mxCellNode(
        `n${i}`,
        compactLabel(table),
        col * 260 + 40,
        row * 120 + 60,
        220,
        70,
        isMember ? categoryColor(table.category) : "#f1f5f9",
        isMember ? "#ffffff" : "#475569",
        !isMember,
      ),
    );
  });

  // Bug 2/5: Parallele Kanten fächern + Kardinalitätsmarker, wie im Big Picture
  const catBusinessEdges = model.edges.filter(
    (e) => !isAuditEdge(e) && idOf.has(e.fromTable) && idOf.has(e.toTable),
  );
  const catParallel = new Map<string, number>();
  for (const e of catBusinessEdges) {
    const key = `${e.toTable}->${e.fromTable}`;
    catParallel.set(key, (catParallel.get(key) ?? 0) + 1);
  }
  const catSeen = new Map<string, number>();

  let edgeIndex = 0;
  for (const edge of catBusinessEdges) {
    const key = `${edge.toTable}->${edge.fromTable}`;
    const groupSize = catParallel.get(key) ?? 1;
    const groupIdx = catSeen.get(key) ?? 0;
    catSeen.set(key, groupIdx + 1);
    const t = groupSize > 1 ? 0.2 + groupIdx * (0.6 / (groupSize - 1)) : -1;

    let extraStyle = "";
    const geom: EdgeGeom = {};

    if (edge.toTable === edge.fromTable) {
      // Bug 3: Selbstreferenz — sichtbarer Loop rechts neben der Box
      const selfIdx = ordered.indexOf(edge.toTable);
      const selfTable = included.get(edge.toTable);
      if (selfTable && selfIdx >= 0) {
        const col = selfIdx % 3;
        const row = Math.floor(selfIdx / 3);
        const x = col * 260 + 40;
        const y = row * 120 + 60;
        extraStyle =
          "exitX=1;exitY=0.25;exitDx=0;exitDy=0;entryX=1;entryY=0.75;entryDx=0;entryDy=0";
        geom.points = [{ x: x + 220 + 40, y: y + 25 }];
      }
    } else if (t >= 0) {
      extraStyle = `exitY=${t.toFixed(2)};entryY=${t.toFixed(2)};exitDx=0;exitDy=0;entryDx=0;entryDy=0`;
    }

    extraStyle = extraStyle
      ? `${extraStyle};startArrow=ERone;startFill=0;endArrow=ERmany;endFill=0`
      : "startArrow=ERone;startFill=0;endArrow=ERmany;endFill=0";

    edges.push(
      mxCellEdge(
        `e${edgeIndex}`,
        idOf.get(edge.toTable) ?? "",
        idOf.get(edge.fromTable) ?? "",
        humanizeFkLabel(edge.fromColumn),
        {
          ...geom,
          extraStyle,
        },
        edge.kind === "logical",
      ),
    );
    edgeIndex += 1;
  }
  return drawioWrap(`cat-${catKey}`, nodes.join("\n"), edges.join("\n"));
}

function entityDrawio(name: string): string {
  const table = tablesByName.get(name);
  if (!table) return "";

  const neighbors: Table[] = [];
  const seen = new Set<string>([name]);
  const relEdges: { from: string; to: string; column: string; dashed: boolean }[] = [];
  for (const edge of model.edges) {
    if (edge.fromTable !== name && edge.toTable !== name) continue;
    relEdges.push({
      from: edge.fromTable,
      to: edge.toTable,
      column: edge.fromColumn,
      dashed: edge.kind === "logical",
    });
    for (const tableName of [edge.fromTable, edge.toTable]) {
      if (seen.has(tableName)) continue;
      seen.add(tableName);
      const related = tablesByName.get(tableName);
      if (related) neighbors.push(related);
    }
  }

  const nodes: string[] = [];
  const edges: string[] = [];
  const idOf = new Map<string, string>();
  idOf.set(name, "main");
  neighbors.forEach((nb, i) => {
    idOf.set(nb.name, `nb${i}`);
  });

  // Haupttabelle: alle Felder auflisten (PK markiert)
  const fieldLines = table.columns
    .map((column) => (column.isPrimaryKey ? `PK ${column.name}` : column.name))
    .join("<br>");
  const mainHeight = 40 + table.columns.length * 16;
  nodes.push(
    mxCellNode(
      "main",
      `<b>${table.name}</b><br>${fieldLines}`,
      40,
      40,
      280,
      mainHeight,
      categoryColor(table.category),
      "#ffffff",
    ),
  );

  // Nachbarn: kompakt, grau
  let y = 40;
  for (const nb of neighbors) {
    nodes.push(
      mxCellNode(
        idOf.get(nb.name) ?? "",
        compactLabel(nb),
        480,
        y,
        200,
        70,
        "#f1f5f9",
        "#475569",
        true,
      ),
    );
    y += 120;
  }

  // Bug 2/5: Parallele Kanten fächern + Kardinalitätsmarker wie im Big Picture
  const entParallel = new Map<string, number>();
  for (const e of relEdges) {
    const key = `${e.to}->${e.from}`;
    entParallel.set(key, (entParallel.get(key) ?? 0) + 1);
  }
  const entSeen = new Map<string, number>();

  relEdges.forEach((edge, i) => {
    const key = `${edge.to}->${edge.from}`;
    const groupSize = entParallel.get(key) ?? 1;
    const groupIdx = entSeen.get(key) ?? 0;
    entSeen.set(key, groupIdx + 1);
    const t = groupSize > 1 ? 0.2 + groupIdx * (0.6 / (groupSize - 1)) : -1;

    let extraStyle = "";
    const geom: EdgeGeom = {};

    if (edge.from === edge.to) {
      // Bug 3: Selbstreferenz der Haupttabelle — Loop rechts neben der Feld-Box
      extraStyle = "exitX=1;exitY=0.25;exitDx=0;exitDy=0;entryX=1;entryY=0.75;entryDx=0;entryDy=0";
      geom.points = [{ x: 40 + 280 + 60, y: 40 + 25 }];
    } else if (t >= 0) {
      extraStyle = `exitY=${t.toFixed(2)};entryY=${t.toFixed(2)};exitDx=0;exitDy=0;entryDx=0;entryDy=0`;
    }

    extraStyle = extraStyle
      ? `${extraStyle};startArrow=ERone;startFill=0;endArrow=ERmany;endFill=0`
      : "startArrow=ERone;startFill=0;endArrow=ERmany;endFill=0";

    edges.push(
      mxCellEdge(
        `e${i}`,
        idOf.get(edge.to) ?? "",
        idOf.get(edge.from) ?? "",
        humanizeFkLabel(`${edge.from}.${edge.column}`),
        { ...geom, extraStyle },
        edge.dashed,
      ),
    );
  });

  return drawioWrap(
    `ent-${name.replace(/[^a-zA-Z0-9_-]/g, "_")}`,
    nodes.join("\n"),
    edges.join("\n"),
  );
}

// ---------------------------------------------------------------------------
// Dateien schreiben
// ---------------------------------------------------------------------------

const bigMmd = bigPictureMmd();
const categoryMmds = new Map<string, string>();
for (const category of model.categories) {
  categoryMmds.set(category.key, categoryMmd(category.key));
}
const entityMmds = new Map<string, string>();
for (const table of model.tables) {
  entityMmds.set(table.name, entityMmd(table.name));
}

mkdirSync(join(OUT_DIR, "categories"), { recursive: true });
mkdirSync(join(OUT_DIR, "entities"), { recursive: true });

writeFileSync(join(OUT_DIR, "big-picture.mmd"), bigMmd);
writeFileSync(join(OUT_DIR, "erd.drawio"), bigPictureDrawio());
for (const [key, mmd] of categoryMmds) {
  writeFileSync(join(OUT_DIR, "categories", `${key}.mmd`), mmd);
  writeFileSync(join(OUT_DIR, "categories", `${key}.drawio`), categoryDrawio(key));
}
for (const [name, mmd] of entityMmds) {
  writeFileSync(join(OUT_DIR, "entities", `${name}.mmd`), mmd);
  writeFileSync(join(OUT_DIR, "entities", `${name}.drawio`), entityDrawio(name));
}

// ---------------------------------------------------------------------------
// HTML-Viewer — Diagramm-Quellen inlined, damit file:// ohne Server funktioniert
// ---------------------------------------------------------------------------

const diagrams = {
  big: bigMmd,
  categories: Object.fromEntries(categoryMmds),
  entities: Object.fromEntries(entityMmds),
};

const stats = {
  tableCount: model.tables.length,
  columnCount: model.tables.reduce((sum, t) => sum + t.columns.length, 0),
  fkCount: model.edges.length,
  sfRefCount: model.externalReferences.length,
  categoryCount: model.categories.length,
};

const auditEdgeCount = model.edges.filter(isAuditEdge).length;
const businessEdgeCount = model.edges.length - auditEdgeCount;
const logicalEdgeCount = model.edges.filter((e) => e.kind === "logical").length;

// Der Nicht-CRUD-Katalog wird zur Build-Zeit aus seiner Markdown-Quelle
// gerendert (optional — fehlt die Datei, bleibt der Tab leer).
const nichtCrudPath = join(REPO_ROOT, NICHT_CRUD_SOURCE_DIR, NICHT_CRUD_SOURCE_FILE);
const nichtCrudHtml = existsSync(nichtCrudPath)
  ? renderMarkdown(readFileSync(nichtCrudPath, "utf-8"), {
      sourceDir: NICHT_CRUD_SOURCE_DIR,
      outputDir: VIEWER_OUTPUT_DIR,
    })
  : "";

// Viewer-Template: spark/scripts/erd/viewer-template.html
// Daten werden an den {{...}}-Platzhaltern injiziert.
const viewerTemplate = readFileSync(
  join(dirname(fileURLToPath(import.meta.url)), "viewer-template.html"),
  "utf-8",
);
const html = viewerTemplate
  .replace("{{MODEL}}", JSON.stringify(model))
  .replace(
    "{{STATS}}",
    JSON.stringify({ ...stats, businessEdgeCount, auditEdgeCount, logicalEdgeCount }),
  )
  .replace("{{DIAGRAMS}}", JSON.stringify(diagrams))
  .replace("{{SFREFS}}", JSON.stringify(model.externalReferences))
  .replace("{{NICHT_CRUD_HTML}}", JSON.stringify(nichtCrudHtml))
  .replace("{{NICHT_CRUD_SOURCE}}", `${NICHT_CRUD_SOURCE_DIR}/${NICHT_CRUD_SOURCE_FILE}`)
  .replace("{{BUSINESS_DESCRIPTIONS}}", JSON.stringify(businessDescriptions))
  .replace("{{BUSINESS_DESCRIPTIONS_SHORT}}", JSON.stringify(businessDescriptionsShort))
  .replace("{{CATEGORY_CSS_VARS}}", categoryCssVars())
  .replace("{{CATEGORY_CSS_CLASSES}}", categoryCssClasses());

writeFileSync(join(OUT_DIR, "erd.html"), html);

console.log(
  `erd/ generated: big-picture.mmd, ${model.categories.length} category diagrams (.mmd + .drawio), ${model.tables.length} entity diagrams (.mmd + .drawio), erd.drawio, erd.html`,
);
